
[tasks.tree]
script = '''
tree \
  --dirsfirst \
  --noreport \
  -I \
  "target|cache|Catalog.md|*.json|*.lock|*.toml" | sed 's/^/    /' > Catalog.md
'''

# ================================================================================================
# cargo
# ================================================================================================

[tasks.cargo-fxderive]
cwd = "./fx-derive"
command = "cargo"
args = ["${@}"]

[tasks.cargo-fx]
cwd = "./fx"
command = "cargo"
args = ["${@}"]

# ================================================================================================
# sum
# ================================================================================================

[tasks.cargo]
dependencies=[
  "cargo-fxderive",
  "cargo-fx",
]
